### PR TITLE
Hello, Partner!

### PR DESCRIPTION
**Pull request by RaivisCerpinskis**
Ich finde dein Hintergrund den du Erstellt hast ziehmlich gut.

### CODE REVIEW

**Comment by SerapAkbulut** [comment]
Danke :)

**Comment by RaivisCerpinskis** [comment]
Bitte https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2FUx5cQbO_ybw%2Fmaxresdefault.jpg&tbnid=sXg33ilvpIAKSM&vet=12ahUKEwj7v-T3oKCDAxVigv0HHbBbCe8QMygMegUIARCNAQ..i&imgrefurl=https%3A%2F%2Fdudeproducts.com%2Fblogs%2Fdude-blog%2Fgiga-chad-meme&docid=Wy4ZNsiWz4RECM&w=1280&h=720&q=gigachad&client=firefox-b-d&ved=2ahUKEwj7v-T3oKCDAxVigv0HHbBbCe8QMygMegUIARCNAQ###   :)

**Comment by RaivisCerpinskis** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fmakeagif.com%2Fgif%2Ffrog-laughing-meme-gEBrYE&psig=AOvVaw1FLOCN7BbSLmXp4Bbf4GVO&ust=1703238797766000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCOi7jY-hoIMDFQAAAAAdAAAAABAG  Hier für die Motivation

**Comment by RaivisCerpinskis** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.polygon.com%2Fguides%2F23871976%2Flies-of-p-scrapped-watchman-how-to-beat&psig=AOvVaw2twWUpCRUKhciONoiCAxf_&ust=1703239030178000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCLiy7P2hoIMDFQAAAAAdAAAAABAD  HAHAHAHAHAHAHAHAH xD

**Pull request merged**
